### ISSUE TITLE
1st Run Error

### ISSUE THREAD

**Issue by brckd6** [bzier/gym-mupen64plus#12] opened 2017-04-20 03:27 UTC
Hello, I'm attempting to get all of this working. This is what I keep getting after I run your simple test code. Any help would be greatly appreciated!

('ControllerHTTPServer started on port ', 8082)
initial_disp: :0
Starting xvfb with command: ['Xvfb', ':1', '-screen', '0', '640x480x24', '-fbdir', '/dev/shm']
(EE) 
Fatal server error:
(EE) Server is already active for display 1
	If this server is no longer running, remove /tmp/.X1-lock
	and start again.
(EE) 
unlink: No such file or directory
unlink  failed, No such file or directoryChanged DISPLAY to: :1
Starting emulator with comand: ['vglrun', 'mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/brad/code/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 63, in __init__
    self.xvfb_process, self.emulator_process = self._start_emulator(rom_name=rom_name)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 225, in _start_emulator
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Close called!

**Comment by bzier** [comment] 2017-04-22 18:30
@brckd6, sorry it's taken me a few days to get back to you. I was out of town for a week and haven't gotten caught up on things since I got back yet.

The error you are getting is caused by the X Display being in use. I've encountered this in certain scenarios where the environment crashes, but the XVFB process is still running, and therefore still using the X Display. Run `ps aux | grep xvfb` to see if this is the case. If so, just go ahead and kill the process and that should fix it. I haven't figured out why XVFB keeps running in some situations, but closes in others. Something on my list of things to do.

The other possibility that comes to mind is that your system might already be using display :1 for something else. If this is the case, you can change the X Display for the environment in the config file to something that isn't in use (e.g. :2 or :3 or something).

If neither of those things fix the issue, let me know and I can see what else I can come up with.

**Comment by bzier** [comment] 2017-04-22 18:31
Oh and one other thing you could try, if you're sure nothing is truly using the X Display, as the error message states:
"Server is already active for display 1
If this server is no longer running, remove /tmp/.X1-lock
and start again."

**Comment by brckd6** [comment] 2017-04-22 20:39
Thanks, that got me past that and onto this error:

[2017-04-22 15:37:54,219] Making new env: Mario-Kart-Luigi-Raceway-v0
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 62, in __init__
    self.controller_server, self.controller_server_thread = self._start_controller_server()
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 153, in _start_controller_server
    config['ACTION_TIMEOUT'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 305, in __init__
    super(ControllerHTTPServer, self).__init__(server_address, self.ControllerRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Close called!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 169, in close
    self._close()
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 149, in _close
    self._stop_controller_server()
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 162, in _stop_controller_server
    if self.controller_server is not None:
AttributeError: 'MarioKartLuigiRacewayEnv' object has no attribute 'controller_server'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 169, in close
    self._close()
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 149, in _close
    self._stop_controller_server()
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 162, in _stop_controller_server
    if self.controller_server is not None:
AttributeError: 'MarioKartLuigiRacewayEnv' object has no attribute 'controller_server'

**Comment by bzier** [comment] 2017-04-23 01:20
Hmm that's odd. The actual error is "Address already in use". Make sure you're not running anything else on port 8082. Also make sure there aren't any other processes that haven't shutdown properly. If the environment is crashing, it's possible that one of the processes is still running.

Out of curiosity, what was the cause of your first issue?

**Comment by brckd6** [comment] 2017-04-23 02:20
Well, I'm back to getting the 1st error. I might not have even gotten it fixed. I'm not longer getting the X window already in use error though. I'm going to paste this even though it's a bit of recap from earlier.

initial_disp: :0
Starting xvfb with command: ['Xvfb', ':1', '-screen', '0', '640x480x24', '-fbdir', '/dev/shm']
Changed DISPLAY to: :1
Starting emulator with comand: ['vglrun', 'mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/brad/code/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Traceback (most recent call last):
  File "play.py", line 67, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 63, in __init__
    self.xvfb_process, self.emulator_process = self._start_emulator(rom_name=rom_name)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 225, in _start_emulator
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bzier** [comment] 2017-04-23 05:55
Make sure the program `vglrun` is available on your machine.
Make sure the program `mupen64plus` is available.
Check that the input driver exists here:
`/usr/local/lib/mupen64plus/mupen64plus-input-bot.so`
Check that you have the ROM file in this directory and that the filename matches as well (case sensitive too):
`/home/brad/code/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64`

**Comment by brckd6** [comment] 2017-04-23 13:53
I appreciate you helping me work through this. I didn't have vglrun on the machine, so it made it further but now I get this error. I've tried a few different things but each time mupen64plus gets hung up and I can't seem to kill it so I have to reboot to try it again.

[2017-04-23 08:49:01,584] Making new env: Mario-Kart-Luigi-Raceway-v0
('ControllerHTTPServer started on port ', 8082)
initial_disp: :0
Starting xvfb with command: ['Xvfb', ':3', '-screen', '0', '640x480x24', '-fbdir', '/dev/shm']
Changed DISPLAY to: :3
Starting emulator with comand: ['vglrun', 'mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/brad/code/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Calling wx.App() with DISPLAY: :3
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
UI-Console:             Includes support for MIPS r4300 Debugger.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 63, in __init__
    self.xvfb_process, self.emulator_process = self._start_emulator(rom_name=rom_name)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 232, in _start_emulator
    self.screen = wx.ScreenDC()
wx._core.PyNoAppError: The wx.App object must be created first!
Close called!
Core: Goodname: Mario Kart 64 (U) [!]
Core: Name: MARIOKART64         
Core: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF
Core: CRC: 3E5055B6 2E92DA52
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1446
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus Bot Input Plugin' v0.0.1
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: Mupen64Plus Bot Input Plugin version 0.0.1 initialized.
Video: SSE processing enabled.
Video: Found ROM 'Mario Kart 64', CRC b655503e52da922e-45
Video: Enabled hacks for game: 'MARIOKART64'
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_SWAP_CONTROL to 0. (it's 24)
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video Warning: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: NVIDIA Corporation - GeForce GTX 1070/PCIe/SSE2 : 4.5.0 NVIDIA 375.39
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f5e341a06e0
Sending SHUTDOWN response

**Comment by bzier** [comment] 2017-04-23 14:16
No problem, I'm happy to help. I'm hoping by having another person walk through this I can improve the readme and the setup process and hopefully make things a little more stable too.

So now it looks like wx is failing to start for some reason. It is attempting to start here:
`Calling wx.App() with DISPLAY: :3`
But it must have failed because you're also getting this:
`wx._core.PyNoAppError: The wx.App object must be created first!`

To simplify things a bit and see if we can get you up and running, try running without XVFB. This will run the emulator on your normal X Display as a regular window. If we can get that working, then we can try to move on with XVFB. In the config file change this to false and give it another shot:
`USE_XVFB: false`
Then let me know what you get.

Also, if you're having trouble killing a process, try `kill -9` and see if that makes a difference. You shouldn't have to reboot every time.

**Comment by brckd6** [comment] 2017-04-23 14:32
This time it actually launched a mupen window before it crashes.

initial_disp: :0
Starting emulator with comand: ['mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/brad/code/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Calling wx.App() with DISPLAY: :0
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
UI-Console:             Includes support for MIPS r4300 Debugger.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 63, in __init__
    self.xvfb_process, self.emulator_process = self._start_emulator(rom_name=rom_name)
  File "/home/brad/code/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 232, in _start_emulator
    self.screen = wx.ScreenDC()
wx._core.PyNoAppError: The wx.App object must be created first!
Close called!
Core: Goodname: Mario Kart 64 (U) [!]
Core: Name: MARIOKART64         
Core: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF
Core: CRC: 3E5055B6 2E92DA52
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1446
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus Bot Input Plugin' v0.0.1
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: Mupen64Plus Bot Input Plugin version 0.0.1 initialized.
Video: SSE processing enabled.
Video: Found ROM 'Mario Kart 64', CRC b655503e52da922e-45
Video: Enabled hacks for game: 'MARIOKART64'
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_SWAP_CONTROL to 0. (it's 24)
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video Warning: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: NVIDIA Corporation - GeForce GTX 1070/PCIe/SSE2 : 4.5.0 NVIDIA 375.39
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f3855d976e0
Sending SHUTDOWN response

**Comment by bzier** [comment] 2017-04-23 14:57
That's weird, it is still complaining about the same thing. Unfortunately I'm gonna be offline mode of the day today, and I'm out of ideas at the moment. I'll take a closer look when I can. Until then, play around with wx and see if you can get it to be happy. Specifically here:
https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L230

It may be helpful to comment out the line or two above it where it is invoking the emulator process, just to simplify things for a bit. It is the following line that is failing when it attempts to grab the ScreenDC. See if you can get that call working. Let me know where you end up and I'll see what else I can do to help.

**Comment by emomicrowave** [comment] 2017-05-05 09:01
@brckd6 Did you manage to get it working?

**Comment by emomicrowave** [comment] 2017-05-05 12:29
I also had this issue: 
https://github.com/bzier/gym-mupen64plus/issues/12

So, after installing `vglrun` and setting `USE_XVFB: false` in `config.yml` and modifying the code a bit I managed to get it working. I assume the `wx.App()` object should be stored, otherwise the interpreter deletes the object, since there are no references to it. 

You can view the Pull Request to see the changes I made.

**Comment by bzier** [comment] 2017-05-05 15:09
Thanks @emomicrowave. I'm glad you were able to get it working and your theory sounds reasonable. I'll go ahead and merge it in and hopefully @brckd6 can confirm it works too.

Out of curiosity, after resolving that wx issue, are you able to run it successfully with `USE_XVFB: true` as well, or do you still need that turned off?

**Comment by emomicrowave** [comment] 2017-05-05 15:36
I tried it, but the mupen window didn't appear until the start of the race. And then the AI didn't want to do anything, it was getting the same signal from the input bot. With `USE_XVFB: false` however, the AI was getting data from the model and different signals from the input bot, so it was working way better.

**Comment by bzier** [comment] 2017-05-06 00:51
I would expect that the window wouldn't show up until the start of the race. It doesn't call to render until the episode is ready (at the start of the race). However, the behavior should be the same whether using XVFB or not. Whatever shows in the window should be exactly what the AI is getting as it's data. If that shows the race, it should be good. I'll have to dive in a little deeper later...maybe this weekend or next. For now, at least you can proceed without XVFB.

**Comment by bzier** [comment] 2017-11-12 02:03
Since no one has commented on this in months, I'm going to go ahead and close it.

**Closed by bzier** 2017-11-12 02:03 UTC
Labels: setup-issues
